routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'Site\SiteController@index')->name('site.index');

Route::get('portfolio', 'Site\SiteController@portfolio')->name('site.portfolio');
Route::get('portfolio/{slug}', 'Site\SiteController@showPortfolio')->name('site.show-portfolio');

Route::get('habilidades', 'Site\SiteController@skills')->name('site.skills');

Route::get('sobre', 'Site\SiteController@about')->name('site.about');

Route::get('contato', 'Site\SiteController@contact')->name('site.contact');
Route::post('mensagem', 'Site\SiteController@message')->name('site.message');

//Route::get('/home', 'HomeController@index')->name('home');



Route::prefix('admin')->group(function () {
    // Authentication Routes...
    Route::get('login', ['as' => 'login','uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => '','uses' => 'Auth\LoginController@login']);
    Route::post('logout', ['as' => 'logout','uses' => 'Auth\LoginController@logout']);
  
    // Password Reset Routes...
    Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset', ['as' => 'password.request','uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/reset', ['as' => '','uses' => 'Auth\ResetPasswordController@reset']);
    Route::get('password/reset/{token}', ['as' => 'password.reset','uses' => 'Auth\ResetPasswordController@showResetForm']);
  
    // Registration Routes...
    //Route::get('register', ['as' => 'register','uses' => 'Auth\RegisterController@showRegistrationForm']);
    //Route::post('register', ['as' => '','uses' => 'Auth\RegisterController@register']);

    Route::get('/', 'Admin\DashboardController@index')->name('home-admin');
    Route::get('dashboard', 'Admin\DashboardController@index')->name('home-admin');

    Route::resource('users', 'Admin\UsersController', ['except' => ['show']]);
    
    Route::resource('portfolio', 'Admin\PortfolioController', ['except' => ['show']]);
    Route::post('portfolio/order', 'Admin\PortfolioController@order')->name('portfolios.order');
    Route::get('portfolio/images/delete/{id}/{p_id}', 'Admin\PortfolioController@deleteImage')->name('portifolio.delete.image');
    
    Route::resource('skills', 'Admin\SkillsController', ['except' => ['show']]);
    Route::post('skills/order', 'Admin\SkillsController@order')->name('skills.order');

    Route::resource('certificates', 'Admin\CertificatesController', ['except' => ['show']]);

    Route::get('messages', 'Admin\MessagesController@index')->name('messages.index');




    /*
    Route::resource('users', 'UsersController', [
    'only' => ['index', 'show']
    ]);

    Route::resource('monkeys', 'MonkeysController', [
        'except' => ['edit', 'create']
    ]);
    */
});

app/Skill.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Skill extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'image', 'order', 'slug'
    ];
    
    public function certificates()
    {
        return $this->belongsToMany('App\Certificate');
    }

    public function portfolios()
    {
        return $this->belongsToMany('App\Portfolio');
    }
}

app/Http/Controllers/Admin/SkillsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SkillsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $skills = \App\Skill::orderBy('order', 'ASC')->get();
        return view('admin.skills.index', compact('skills'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.skills.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required|string|max:255',
            'description' => 'required',
            'image' => 'required',
        ]);


        $fileName = null;
        if (request()->hasFile('image')) {
            $file = request()->file('image');
            $fileName = str_slug(preg_replace('/\..+$/', '', $file->getClientOriginalName())) . '.' . $file->getClientOriginalExtension();
        }

        $skill = \App\Skill::create([
            'name' => $request['name'],
            'slug' => str_slug($request['name']),
            'description' => $request['description'],
            'image' => $fileName
        ]);
        $file->move(public_path('/images/skills/' . $skill->id), $fileName);
        return response()->redirectToRoute('skills.index')->with('success', 'Habilidade criada com sucesso!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!$skill = \App\Skill::find($id)) {
            return response()->redirectToRoute('skills.index')->with('error', 'Habilidade não encontrada!');
        } else {
            return view('admin.skills.edit', compact('skill'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (!$skill = \App\Skill::find($id)) {
            return response()->redirectToRoute('skills.index')->with('error', 'Habilidade não encontrada!');
        } else {
            $val = [
                'name' => 'required|string|max:255',
                'description' => 'required'
            ];

            $fileName = $skill->image;
            if (request()->hasFile('image')) {
                $file = request()->file('image');
                $fileName = str_slug(preg_replace('/\..+$/', '', $file->getClientOriginalName())) . '.' . $file->getClientOriginalExtension();
                $val['image'] = 'required';
            }
            request()->validate($val);

            if (request()->hasFile('image')) {
                $file->move(public_path('/images/skills/' . $skill->id), $fileName);
            }

            $skill->fill([
                'name' => $request['name'],
                'slug' => str_slug($request['name']),
                'description' => $request['description'],
                'image' => $fileName
            ]);
            $skill->save();
            return response()->redirectToRoute('skills.index')->with('success', 'Habilidade alterada com sucesso!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!$skill = \App\Skill::find($id)) {
            return response()->redirectToRoute('skills.index')->with('error', 'Habilidade não encontrada!');
        } else {
            $skill->delete();
            return response()->redirectToRoute('skills.index')->with('success', 'Habilidade removida com sucesso!');
        }
    }

    /**
     * Order the skills
     *
     * @return \Illuminate\Http\Response
     */
    public function order(Request $request)
    {
        $id = $request['id'];
        $order = $request['order'];
        if ($skill = \App\Skill::find($id)) {
            $skill->fill([
                'order' => $order
            ]);
            $skill->save();
        }
    }
}

resources/views/admin/skills/create.blade.php
@extends('layouts.admin')

@push('styles')
    
@endpush

@section('content')
<div class="right_col" role="main">
    <div class="">

        <div class="page-title">
            <div class="title_left">
                <h3>Habilidades <small>Nova habilidade</small></h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">

                    <form action="{{ route('skills.store') }}" method="post" class="form-horizontal form-label-left" novalidate id="demo-form2" enctype="multipart/form-data">

                        @include('admin.skills.form')

                        @component('admin.components.form-button')
                            Enviar
                        @endcomponent
                    </form>
                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
    
@endpush

resources/views/admin/skills/edit.blade.php
@extends('layouts.admin')

@push('styles')
    
@endpush

@section('content')
<div class="right_col" role="main">
    <div class="">

        <div class="page-title">
            <div class="title_left">
                <h3>Habilidades <small>Editar habilidade</small></h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">

                    <form action="{{ route('skills.update',['skill' => $skill->id]) }}" method="post" class="form-horizontal form-label-left" novalidate id="demo-form2" enctype="multipart/form-data">
                    {{ method_field('PUT') }}

                        @include('admin.skills.form')

                        @component('admin.components.form-button')
                            Editar
                        @endcomponent
                    </form>
                    
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
    
@endpush

resources/views/admin/skills/form.blade.php
@if($errors->any())
    @component('admin.components.flash-message', ['message' => 'error'])
        <h4><i class="icon fa fa-ban"></i> Foram encontrados os seguintes erros:</h4>
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>        
    @endcomponent
@endif

{!! csrf_field() !!}

<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Nome <span class="required">*</span></label>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <input name="name" class="form-control col-md-7 col-xs-12" type="text" value="{{ $skill->name ?? old('name') }}" required="required">
    </div>
</div>

<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">Descrição <span class="required">*</span></label>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <textarea name="description" class="form-control col-md-7 col-xs-12" required="required">{{ $skill->description ?? old('description') }}</textarea>
    </div>
</div>

<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="image">Imagem <span class="required">*</span></label>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <input name="image" class="col-md-7 col-xs-12" type="file">
    </div>
</div>

resources/views/admin/skills/index.blade.php
@extends('layouts.admin')

@push('styles')

@endpush

@section('content')
<div class="right_col" role="main">
    <div class="">

        <div class="page-title">
            <div class="title_left">
                <h3>Habilidades</h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">

                        @include('admin.includes.flash-message')
                        
                        <table id="datatable-skills" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Ordem</th>
                                    <th>Id</th>
                                    <th>Nome</th>
                                    <th>Imagem</th>
                                    <th>Ações</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($skills as $skill)
                                    <tr class="c-move">
                                        <td>{{ $skill->order }}</td>
                                        <td>{{ $skill->id }}</td>
                                        <td>{{ $skill->name }}</td>
                                        <td><img src="{{ asset('images/skills')}}/{{$skill->id }}/{{ $skill->image }}" alt="{{ $skill->name }}" width="45"></td>
                                        <td>
                                            <a href="{{ route('skills.edit', ['skill' => $skill->id] ) }}" class="btn btn-success btn-xs pull-left" title="Editar"><i class="fa fa-pencil"></i> Editar</a>
                                            @auth  
                                                <form action="{{ route('skills.destroy', ['skill' => $skill->id]) }}" method="post" class="form-inline pull-left form-delete" data-message="Confirma a exclusão da habilidade {{ $skill->name }}?" data-form="deleteForm">
                                                    {!! csrf_field() !!}
                                                    {{ method_field('DELETE') }}
                                                    <button type="submit" class="btn btn-danger btn-xs" title="Apagar"><i class="fa fa-trash"></i> Apagar</button>
                                                </form>                                                  
                                            @endauth
                                            
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>

                        @include('admin.includes.modal')

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')

@endpush