routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'Site\SiteController@index')->name('site.index');

Route::get('portfolio', 'Site\SiteController@portfolio')->name('site.portfolio');
Route::get('portfolio/{slug}', 'Site\SiteController@showPortfolio')->name('site.show-portfolio');

Route::get('habilidades', 'Site\SiteController@skills')->name('site.skills');

Route::get('sobre', 'Site\SiteController@about')->name('site.about');

Route::get('contato', 'Site\SiteController@contact')->name('site.contact');
Route::post('mensagem', 'Site\SiteController@message')->name('site.message');

//Route::get('/home', 'HomeController@index')->name('home');



Route::prefix('admin')->group(function () {
    // Authentication Routes...
    Route::get('login', ['as' => 'login','uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => '','uses' => 'Auth\LoginController@login']);
    Route::post('logout', ['as' => 'logout','uses' => 'Auth\LoginController@logout']);
  
    // Password Reset Routes...
    Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset', ['as' => 'password.request','uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/reset', ['as' => '','uses' => 'Auth\ResetPasswordController@reset']);
    Route::get('password/reset/{token}', ['as' => 'password.reset','uses' => 'Auth\ResetPasswordController@showResetForm']);
  
    // Registration Routes...
    //Route::get('register', ['as' => 'register','uses' => 'Auth\RegisterController@showRegistrationForm']);
    //Route::post('register', ['as' => '','uses' => 'Auth\RegisterController@register']);

    Route::get('/', 'Admin\DashboardController@index')->name('home-admin');
    Route::get('dashboard', 'Admin\DashboardController@index')->name('home-admin');

    Route::resource('users', 'Admin\UsersController', ['except' => ['show']]);
    
    Route::resource('portfolio', 'Admin\PortfolioController', ['except' => ['show']]);
    Route::post('portfolio/order', 'Admin\PortfolioController@order')->name('portfolios.order');
    Route::get('portfolio/images/delete/{id}/{p_id}', 'Admin\PortfolioController@deleteImage')->name('portifolio.delete.image');
    
    Route::resource('skills', 'Admin\SkillsController', ['except' => ['show']]);
    Route::post('skills/order', 'Admin\SkillsController@order')->name('skills.order');

    Route::resource('certificates', 'Admin\CertificatesController', ['except' => ['show']]);

    Route::get('messages', 'Admin\MessagesController@index')->name('messages.index');




    /*
    Route::resource('users', 'UsersController', [
    'only' => ['index', 'show']
    ]);

    Route::resource('monkeys', 'MonkeysController', [
        'except' => ['edit', 'create']
    ]);
    */
});

app/Certificate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Certificate extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'place', 'image', 'code', 'slug'
    ];
    
    public function skills()
    {
        return $this->belongsToMany('App\Skill');
    }
}

app/Http/Controllers/Admin/CertificatesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CertificatesController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $certificates = \App\Certificate::get();
        
        return view('admin.certificates.index', compact('certificates'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $skills = \App\Skill::orderBy('name')->get();
        return view('admin.certificates.create', compact('skills'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required|string|max:255',
            'place' => 'required',
            'code' => 'required',
            'image' => 'required|mimes:jpeg,jpg,png,svg',
        ]);

        $fileName = null;
        if (request()->hasFile('image')) {
            $file = request()->file('image');
            $fileName = str_slug(preg_replace('/\..+$/', '', $file->getClientOriginalName())) . '.' . $file->getClientOriginalExtension();
        }

        $certificate = \App\Certificate::create([
            'name' => $request['name'],
            'slug' => str_slug($request['name']),
            'place' => $request['place'],
            'code' => $request['code'],
            'image' => $fileName
        ]);
        $file->move(public_path('/images/certificates/' . $certificate->id), $fileName);

        if (isset($request['skills'])) {
            $certificate->skills()->attach($request['skills']);
        }
        return response()->redirectToRoute('certificates.index')->with('success', 'Certificado criado com sucesso!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!$certificate = \App\Certificate::find($id)) {
            return response()->redirectToRoute('certificates.index')->with('error', 'Certificado não encontrado!');
        } else {
            $skills = \App\Skill::orderBy('name')->get();
            $s_skills = $certificate->skills()->allRelatedIds()->toArray();
            return view('admin.certificates.edit', compact('certificate', 'skills', 's_skills'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (!$certificate = \App\Certificate::find($id)) {
            return response()->redirectToRoute('certificates.index')->with('error', 'Certificado não encontrado!');
        } else {
            $val = [
                'name' => 'required|string|max:255',
                'place' => 'required',
                'code' => 'required'
            ];

            $fileName = $certificate->image;
            if (request()->hasFile('image')) {
                $file = request()->file('image');
                $fileName = str_slug(preg_replace('/\..+$/', '', $file->getClientOriginalName())) . '.' . $file->getClientOriginalExtension();
                $val['image'] = 'required|mimes:jpeg,jpg,png,svg';
            }
            request()->validate($val);

            if (request()->hasFile('image')) {
                $file->move(public_path('/images/skills/' . $certificate->id), $fileName);
            }

            $certificate->fill([
                'name' => $request['name'],
                'slug' => str_slug($request['name']),
                'place' => $request['place'],
                'code' => $request['code'],
                'image' => $fileName
            ]);
            $certificate->save();

            if (isset($request['skills'])) {
                $certificate->skills()->sync($request['skills']);
            }

            return response()->redirectToRoute('certificates.index')->with('success', 'Certificado alterado com sucesso!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!$certificate = \App\Certificate::find($id)) {
            return response()->redirectToRoute('certificates.index')->with('error', 'Certificado não encontrado!');
        } else {
            $certificate->delete();
            return response()->redirectToRoute('certificates.index')->with('success', 'Certificado removido com sucesso!');
        }
    }
}

resources/views/admin/certificates/create.blade.php
@extends('layouts.admin')

@push('styles')
    
@endpush

@section('content')
<div class="right_col" role="main">
    <div class="">

        <div class="page-title">
            <div class="title_left">
                <h3>Certificados <small>Novo certificado</small></h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">

                    <form action="{{ route('certificates.store') }}" method="post" class="form-horizontal form-label-left" novalidate id="demo-form2" enctype="multipart/form-data">

                        @include('admin.certificates.form')

                        @component('admin.components.form-button')
                            Enviar
                        @endcomponent
                    </form>
                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
    
@endpush

resources/views/admin/certificates/edit.blade.php
@extends('layouts.admin')

@push('styles')
    
@endpush

@section('content')
<div class="right_col" role="main">
    <div class="">

        <div class="page-title">
            <div class="title_left">
                <h3>Certificados <small>Editar certificado</small></h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">

                    <form action="{{ route('certificates.update',['certificate' => $certificate->id]) }}" method="post" class="form-horizontal form-label-left" novalidate id="demo-form2" enctype="multipart/form-data">
                    {{ method_field('PUT') }}

                        @include('admin.certificates.form')

                        @component('admin.components.form-button')
                            Editar
                        @endcomponent
                    </form>
                    
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
    
@endpush

resources/views/admin/certificates/form.blade.php
@if($errors->any())
    @component('admin.components.flash-message', ['message' => 'error'])
        <h4><i class="icon fa fa-ban"></i> Foram encontrados os seguintes erros:</h4>
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>        
    @endcomponent
@endif

{!! csrf_field() !!}

<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Nome <span class="required">*</span></label>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <input name="name" class="form-control col-md-7 col-xs-12" type="text" value="{{ $certificate->name ?? old('name') }}" required="required">
    </div>
</div>

<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="image">Imagem <span class="required">*</span></label>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <input name="image" class="col-md-7 col-xs-12" type="file">
    </div>
</div>

<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="place">Local <span class="required">*</span></label>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <input name="place" class="form-control col-md-7 col-xs-12" type="text" value="{{ $certificate->place ?? old('place') }}" required="required">
    </div>
</div>

<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="code">Code <span class="required">*</span></label>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <input name="code" class="form-control col-md-7 col-xs-12" type="text" value="{{ $certificate->code ?? old('code') }}" required="required">
    </div>
</div>

<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="skills">Habilidades <span class="required">*</span></label>
    <div class="col-md-6 col-sm-6 col-xs-12">
        @php
            if(!isset($s_skills)){
                $s_skills = array();
            }

            
        @endphp
        @foreach($skills as $skill)
            @php
                if (in_array($skill->id, $s_skills)) {
                    $ckecked = 'checked';
                }else{
                    $ckecked = '';
                }
            @endphp
            <div class="checkbox">
                <label>
                    <input type="checkbox" class="flat" name="skills[]" value="{{ $skill->id }}" {{  $ckecked }}> {{ $skill->name }}
                </label>
            </div>
            
        @endforeach
        
    </div>
</div>

resources/views/admin/certificates/index.blade.php
@extends('layouts.admin')

@push('styles')

@endpush

@section('content')
<div class="right_col" role="main">
    <div class="">

        <div class="page-title">
            <div class="title_left">
                <h3>Certificados</h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">

                        @include('admin.includes.flash-message')
                        
                        <table id="datatable-custom" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Nome</th>
                                    <th>Imagem</th>
                                    <th>Imagens</th>
                                    <th>Ações</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($certificates as $certificate)
                                    <tr>
                                        <td>{{ $certificate->id }}</td>
                                        <td>{{ $certificate->name }}</td>
                                        <td>{{ $certificate->place }}</td>
                                        <td>
                                        @php
                                            $skills = $certificate->skills;
                                        @endphp
                                        @foreach($skills as $skill)
                                            <img src="{{ asset('images/skills')}}/{{$skill->id }}/{{ $skill->image }}" alt="{{ $skill->name }}" width="45">
                                        @endforeach
                                        </td>
                                        <td>
                                            <a href="{{ route('certificates.edit', ['certificate' => $certificate->id] ) }}" class="btn btn-success btn-xs pull-left" title="Editar"><i class="fa fa-pencil"></i> Editar</a>
                                            @auth  
                                                <form action="{{ route('certificates.destroy', ['certificate' => $certificate->id]) }}" method="post" class="form-inline pull-left form-delete" data-message="Confirma a exclusão do certificado {{ $certificate->name }}?" data-form="deleteForm">
                                                    {!! csrf_field() !!}
                                                    {{ method_field('DELETE') }}
                                                    <button type="submit" class="btn btn-danger btn-xs" title="Apagar"><i class="fa fa-trash"></i> Apagar</button>
                                                </form>                                                  
                                            @endauth
                                            
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>

                        @include('admin.includes.modal')

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')

@endpush