routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'Site\SiteController@index')->name('site.index');

Route::get('portfolio', 'Site\SiteController@portfolio')->name('site.portfolio');
Route::get('portfolio/{slug}', 'Site\SiteController@showPortfolio')->name('site.show-portfolio');

Route::get('habilidades', 'Site\SiteController@skills')->name('site.skills');

Route::get('sobre', 'Site\SiteController@about')->name('site.about');

Route::get('contato', 'Site\SiteController@contact')->name('site.contact');
Route::post('mensagem', 'Site\SiteController@message')->name('site.message');

//Route::get('/home', 'HomeController@index')->name('home');



Route::prefix('admin')->group(function () {
    // Authentication Routes...
    Route::get('login', ['as' => 'login','uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => '','uses' => 'Auth\LoginController@login']);
    Route::post('logout', ['as' => 'logout','uses' => 'Auth\LoginController@logout']);
  
    // Password Reset Routes...
    Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset', ['as' => 'password.request','uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/reset', ['as' => '','uses' => 'Auth\ResetPasswordController@reset']);
    Route::get('password/reset/{token}', ['as' => 'password.reset','uses' => 'Auth\ResetPasswordController@showResetForm']);
  
    // Registration Routes...
    //Route::get('register', ['as' => 'register','uses' => 'Auth\RegisterController@showRegistrationForm']);
    //Route::post('register', ['as' => '','uses' => 'Auth\RegisterController@register']);

    Route::get('/', 'Admin\DashboardController@index')->name('home-admin');
    Route::get('dashboard', 'Admin\DashboardController@index')->name('home-admin');

    Route::resource('users', 'Admin\UsersController', ['except' => ['show']]);
    
    Route::resource('portfolio', 'Admin\PortfolioController', ['except' => ['show']]);
    Route::post('portfolio/order', 'Admin\PortfolioController@order')->name('portfolios.order');
    Route::get('portfolio/images/delete/{id}/{p_id}', 'Admin\PortfolioController@deleteImage')->name('portifolio.delete.image');
    
    Route::resource('skills', 'Admin\SkillsController', ['except' => ['show']]);
    Route::post('skills/order', 'Admin\SkillsController@order')->name('skills.order');

    Route::resource('certificates', 'Admin\CertificatesController', ['except' => ['show']]);

    Route::get('messages', 'Admin\MessagesController@index')->name('messages.index');




    /*
    Route::resource('users', 'UsersController', [
    'only' => ['index', 'show']
    ]);

    Route::resource('monkeys', 'MonkeysController', [
        'except' => ['edit', 'create']
    ]);
    */
});

resources/views/admin/includes/flash-message.blade.php
@if ($message = Session::get('success'))
<div class="col-sm-8 col-sm-offset-2 col-xs-12">
    <div class="alert alert-success alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert">×</button>	
            <strong>{{ $message }}</strong>
    </div>
</div>
<div class="clear"></div>
@endif

@if ($message = Session::get('error'))
<div class="col-sm-8 col-sm-offset-2 col-xs-12">
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert">×</button>	
            <strong>{{ $message }}</strong>
    </div>
</div>
<div class="clear"></div>
@endif

@if ($message = Session::get('warning'))
<div class="col-sm-8 col-sm-offset-2 col-xs-12">
    <div class="alert alert-warning alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ $message }}</strong>
    </div>
</div>
<div class="clear"></div>
@endif

@if ($message = Session::get('info'))
<div class="col-sm-8 col-sm-offset-2 col-xs-12">
    <div class="alert alert-info alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ $message }}</strong>
    </div>
</div>
<div class="clear"></div>
@endif

resources/views/admin/includes/modal.blade.php
<div class="modal" id="confirm">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h2 class="modal-title text-danger">Confirmação de exclusão</h2>
            </div>
            <div class="modal-body">
                <p>Tem certeza que deseja excluir o registro ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-default pull-right" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-sm btn-danger" id="delete-btn">Apagar</button>
                
            </div>
        </div>
    </div>
</div>

resources/views/admin/includes/sidebar.blade.php
<!-- sidebar menu -->

<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
	<div class="menu_section">
		<h3>General</h3>
		<ul class="nav side-menu">
			<li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a href="{{ route('home-admin') }}">Dashboard</a></li>
				</ul>
			</li>
      <li><a><i class="fa fa-users"></i> Usuários <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a href="{{ route('users.index') }}">Listar</a></li>
          <li><a href="{{ route('users.create') }}">Novo Usuário</a></li>
				</ul>
			</li>
      <li><a><i class="fa fa-desktop"></i> Portfolio <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a href="{{ route('portfolio.index') }}">Listar</a></li>
          <li><a href="{{ route('portfolio.create') }}">Novo portfolio</a></li>
				</ul>
			</li>
			<li><a><i class="fa fa-terminal"></i> Habilidades <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a href="{{ route('skills.index') }}">Listar</a></li>
          <li><a href="{{ route('skills.create') }}">Nova habilidade</a></li>
				</ul>
			</li>
			<li><a><i class="fa fa-code"></i> Certificados <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a href="{{ route('certificates.index') }}">Listar</a></li>
          <li><a href="{{ route('certificates.create') }}">Novo certificado</a></li>
				</ul>
			</li>
			<li><a><i class="fa fa-envelope-o"></i> Mensagens <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a href="{{ route('messages.index') }}">Listar</a></li>
				</ul>
			</li>
		</ul>
	</div>
</div>
<!-- /sidebar menu -->